### ISSUE TITLE
Other Joe dying crashes game

### ISSUE THREAD

**Issue by testman42** [mupfelofen-de/rainbow-joe#1]
After you trigger other Joe to start autorunning in either direction, dude runs off a cliff and dies, and him dying causes game to crash with the following error:
```
Segmentation fault (core dumped)
```
Happens repeatedly on compiled version of the game on Fedora 28 x86_64.

**Comment by testman42** [comment]
Issue does not appear in the latest compiled version.

**Comment by mupfdev** [comment]
The position is tracked by a signed variable. It probably overlapped.
