### ISSUE TITLE
Issue with drawing background

### ISSUE THREAD

**Issue by alkavan** [mupfelofen-de/rainbow-joe#2]
This makes the game a almost unplayable.
Here's a screenshot:

![image](https://user-images.githubusercontent.com/188295/40037613-dc464620-5816-11e8-861a-d9bbdfaf6b4e.png)

Built with:
```
gcc (GCC) 8.1.0
sdl2 2.0.8-8
sdl2_gfx 1:1.0.4-1
sdl2_image 2.0.3-1
sdl2_mixer 2.0.2-2
sdl2_net 1:2.0.1-1
sdl2_ttf 2.0.14-1
```

**Comment by mupfdev** [comment]
This is really odd.
Would you mind giving me some more details about your OS and hardware?
And please try to disable fullscreen mode in the default.ini file and check if the problem still occurs.

Oh, and thanks for trying my demo! Where does your interest come from?

-- Edit:
sdl2_net, sdl2_ttf, sdl2_gfx are no dependencies. The rest should be fine.

**Comment by mupfdev** [comment]
Most likely a hardware problem.
